/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// This function executes in Thread Mode
void generate_interrupt(void){
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	// enable IRQ3 interrupt
	*pISER0 |= (1 << 3);

	// generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);
}

// To change the privilege level you have to change CONTROL Register bit[0] to 1
void change_access_level_unpriv(void){
	// Read from a Special Register
	__asm volatile("MRS R0,CONTROL");
	// Modify with Logical OR
	__asm volatile("ORR R0,R0,#0x01");
	// Write to a Special Register
	__asm volatile("MSR CONTROL,R0");
}

int main(void)
{

	printf("In Thread Mode : Before Interrupt\n");

	void (*fun_ptr)(void);

//	fun_ptr = change_access_level_unpriv();
	// This will cause a fault because the TBit gets flipped to a 0 but it can't run the ARM ISA
	fun_ptr = (void*)0x080001e8;

	fun_ptr();

	printf("In Thread Mode : After Interrupt\n");

    /* Loop forever */
	for(;;);
}

// This function(ISR) executes in Handler Mode
void RTC_WKUP_IRQHandler(void){
	printf("In Handler Mode : ISR\n");
}

void HardFault_Handler(void){
	printf("Hard Fault Detected\n");
	while(1);
}


